name = "vstreets"
main = "src/index.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "vstreets.to", custom_domain = true }
]

[observability]
enabled = true

[[kv_namespaces]]
binding = "vstreets"
id = "1c75a0d7cb2545ee9ce29842641bf467"